kind: pipeline
name: test-pipeline

clone:
  depth: 1

steps:
- name: build-image
  image: plugins/docker
  settings:
    repo: vadden/test-droneci-${DRONE_BRANCH}
    tags:
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  
  when:
    events:
    - push
    - pull_request
    branch:
    - master
