kind: pipeline
name: test-pipeline

clone:
  depth: 1

steps:
- name: build-image
  image: plugins/docker
  settings:
    repo: vadden/test-droneci-${DRONE_BRANCH}
    tags:
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - GITHUB_TOKEN:
        from_secret: github_token
  
  when:
    events:
    - push
    - pull_request
    branch:
    - master
    
- name: notify-on-success
  image: lddsb/drone-dingtalk-message
  settings:
    token: 
      from_secret: dingtalk_token
    type: markdown
    sha_link: true
