stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: vadden/oiugfdcvbnm
      shellScript: ./application
    env:
      DURATION: 10d
      ENDPOINT: https://1262562326756469.cn-hongkong.fc.aliyuncs.com
      REGION: cn-hongkong
      SLS_ENDPOINT: cn-hongkong.log.aliyuncs.com
    envFrom:
    - sourceName: aliyun-secret
      sourceKey: ACCESS_KEY_ID
      targetKey: ACCESS_KEY_ID
    - sourceName: aliyun-secret
      sourceKey: ACCESS_KEY_SECRET
      targetKey: ACCESS_KEY_SECRET
  - runScriptConfig:
      image: golang:latest
      shellScript: printenv
timeout: 60
notification: {}
